### ISSUE TITLE
なんか手伝えることある？

### ISSUE THREAD

**Issue by shmokmt** [nojiri1098/study#3]
自分も卒研手伝えることがあれば手伝いたいのでなんでもいってくれ

**Comment by shmokmt** [comment]
@nojiri1098

**Comment by shmokmt** [comment]
コードフォーマッタとかリントとか仮想環境とかコードのリファクタリングとかだったら簡単にキャッチアップできそう.... 💭

**Comment by nojiri1098** [comment]
ありがとう！
テキトーに書いたコードだから、リファクタしてくれたら嬉しい😄

**Comment by shmokmt** [comment]
@nojiri1098 
使ってるエディタ、Atomだったっけ？

**Comment by nojiri1098** [comment]
@sh-tech
vscodeだよ

**Comment by shmokmt** [comment]
@nojiri1098 
vscodeのjupyter notebook extension 使ってる感じ？
`.ipynb` じゃなくて `.py` で実行できる拡張機能とかあるよね

**Comment by shmokmt** [comment]
`__main__` がいろんなファイルにたくさんあるから、それぞれスクリプトとして実行してるのか？

**Comment by nojiri1098** [comment]
@sh-tech
拡張は特に使ってないや
とりあえずコンソールで python file.py って実行してる

あ、mainがたくさんあるのは動作確認のためで、実際に動かすのは /anfis.py ね

**Comment by shmokmt** [comment]
@nojiri1098 
コンソールで実行してるってことね。おっけー。わかってきた
近いうちにPR出します
動作確認のためのスクリプトは全てCLIで設計して、動的に渡したいオプションを与えられるようにしよかなーーーー

**Comment by nojiri1098** [comment]
@sh-tech
ありがと🙏
