### ISSUE TITLE
学習したモデルをpickleで書き出したい

### ISSUE THREAD

**Issue by nojiri1098** [nojiri1098/study#7]
学習が終わったら `pickle/anfis` とかに書き出す
参考：[Python: オブジェクトを漬物 (Pickle) にする](https://blog.amedama.jp/entry/2015/12/05/132520)

**Comment by nojiri1098** [comment]
参考：[Python: オブジェクトを漬物 (Pickle) にする](https://blog.amedama.jp/entry/2015/12/05/132520)

**Comment by shmokmt** [comment]
たしかにシリアライズはいいかもね
